# Generated by Django 5.2.4 on 2026-03-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Bible', 'Bible'), ('General', 'General'), ('Music', 'Music'), ('Nigeria', 'Nigeria'), ('World', 'World'), ('Sports', 'Sports')], max_length=50),
        ),
    ]
