# Generated by Django 5.2.4 on 2026-03-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameroom_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
    ]
