# Generated by Django 5.2.4 on 2026-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_multiplayerplayer_playeranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Bible', 'Bible'), ('General', 'General'), ('Music', 'Music'), ('Nigeria', 'Nigeria'), ('World', 'World'), ('Sport', 'Sport'), ('The Elevation Church', 'The Elevation Church')], max_length=50),
        ),
    ]
