# Generated by Django 5.2.4 on 2026-03-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
