# Generated by Django 5.2.4 on 2026-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gameroom_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
